### ISSUE TITLE
getTransaction function

### ISSUE THREAD

**Issue by EternalQuasar0206** [EternalQuasar0206/OpenPixSDK#15]

**Comment by EternalQuasar0206** [comment]
Solved in [bbfd7f84d04589a5242916268f0f4713e2d8033a](https://github.com/EternalQuasar0206/OpenPixSDK/commit/bbfd7f84d04589a5242916268f0f4713e2d8033a)

**Comment by daniloab** [comment]
are you merging directly into the main?
